module.exports = {
    HTML_DATE_FORMAT: "YYYY-MM-DD",
    HTML_TIME_FORMAT_UNTIL_MINUTES: "HH:mm",
    DATE_TIME_FORMAT_UNTIL_MINUTES : "YYYY-MM-DD HH:mm",
    DATE_TIME_FORMAT_UNTIL_SECONDS: "YYYY-MM-DD HH:mm:ss",
    DATE_TIME_FORMAT_UNTIL_MINUTES_WITH_MERIDIEM: "YYYY-MM-DD hh:mm A"
};